# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dc2d985912486eb0f7b7e43f928b59cfa018fb54c3c65dfef8391e5ecbcd54d3bb5321521b88a2bb89832d58d78d64252ba39558931c5dcc2df4cd3471f1e9ba

test:
  secret_key_base: 1c872aefbafbf7306a529340b4ea36da66099095b694d0f4cc3bb9c064c3dbd0e1778bcbdcaa2bf3d9975df68d140a87438c8ac4ddb4274adf842cf111f4d234

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
